### ISSUE TITLE
how to done pause and reset using react-timer-mixin

### ISSUE THREAD

**Issue by shaikhussian** [reactjs/react-timer-mixin#11]
hai i am using this module for pause and reset time but i am struggling that how to pause the timer,stop the timer,reset the timer, here i am attaching the image of the view 

![demo-timer](https://cloud.githubusercontent.com/assets/11956308/15359107/731b57fe-1d25-11e6-94c9-1cd5636d9882.png)

plaese help me how to done i used 

```
TimerMixin.setTimeout(
      () => { console.log('I do not leak!'); },
      5000
    );
```

but timer not stop,help me that how to pause the timer

**Comment by shaikhussian** [comment]
Please respond for it

**Comment by aweary** [comment]
@shaikhussian `react-timer-mixin` isn't actually meant to provide an actual timer interface. It's just a tool to help manage `setTimeout` / `setInterval` / `setImmediate` calls in a React component.

If you wanted to implement a pausable timer you'd have to do that yourself. You could track the current time in `this.state.time` and have a like `pauseTimer` and `resumeTimer` that cleared and set the `setInterval` call, respectively.
