### ISSUE TITLE
React 13.3 server error: cancelAnimationFrame is not defined

### ISSUE THREAD

**Issue by super-cache-money** [reactjs/react-timer-mixin#2]
As the title says, I'm having problems using this with server rendering.
I'm not using the mixin on the server, just requiring it. 

It throws: 

```
 [ReferenceError: cancelAnimationFrame is not defined]
```

**Comment by sophiebits** [comment]
Which mixin?

**Comment by super-cache-money** [comment]
This one, react-timer-mixin.

**Comment by sophiebits** [comment]
Oh, sorry. Missed which repo this was for.

**Comment by super-cache-money** [comment]
Ha, it's cool, thought it was a trick question.

**Comment by usmanasif** [comment]
I am also getting this error, how to resolve it ?
