### ISSUE TITLE
Why is this necessary?

### ISSUE THREAD

**Issue by wle8300** [reactjs/react-timer-mixin#6]
Can't you just use a private variable on the component for your timers, and then use the lifecycle method, `componentWillUnmount`, to clear appropriate "timeouts" and "intervals"?

This mixin is uses more power than it needs to. This use case could be solved simply by using a documented & official lifecycle method.

**Comment by sophiebits** [comment]
Yes. This makes it harder to forget. What you suggest certainly works and is the approach I usually use.
